/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#005048",
        "secondary-fixed": "#85f6e5",
        "outline-variant": "#c6c5d4",
        "error": "#ba1a1a",
        "secondary": "#006a60",
        "surface-container-highest": "#e2e1ed",
        "primary": "#000666",
        "on-surface-variant": "#454652",
        "on-tertiary-fixed": "#390c00",
        "surface-container-low": "#f3f2fe",
        "tertiary-fixed": "#ffdbd0",
        "primary-fixed": "#e0e0ff",
        "surface-container": "#eeedf8",
        "surface-tint": "#4c56af",
        "tertiary": "#380b00",
        "background": "#fbf8ff",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#e17c5a",
        "surface-dim": "#dad9e4",
        "on-primary-fixed-variant": "#343d96",
        "on-primary-fixed": "#000767",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb59d",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#007166",
        "error-container": "#ffdad6",
        "primary-container": "#1a237e",
        "secondary-container": "#85f6e5",
        "inverse-primary": "#bdc2ff",
        "on-primary-container": "#8690ee",
        "inverse-surface": "#2f3038",
        "outline": "#767683",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#67d9c9",
        "surface-variant": "#e2e1ed",
        "surface-bright": "#fbf8ff",
        "tertiary-container": "#5c1800",
        "inverse-on-surface": "#f1f0fb",
        "on-background": "#1a1b23",
        "surface-container-high": "#e8e7f2",
        "on-surface": "#1a1b23",
        "primary-fixed-dim": "#bdc2ff",
        "on-secondary-fixed": "#00201c",
        "on-tertiary-fixed-variant": "#7b2e12",
        "on-error": "#ffffff",
        "surface": "#fbf8ff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
